server:
  port: 8084
spring:
  application:
    name: client-feign
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true
